artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/kousik23naskar/mlproject_data/raw/main/tmdb_5000_data_kaggle.tar.gz
  local_data_file: artifacts/data_ingestion/data.tar.gz
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir1: artifacts/data_ingestion/tmdb_5000_data_kaggle/tmdb_5000_movies.csv
  unzip_data_dir2: artifacts/data_ingestion/tmdb_5000_data_kaggle/tmdb_5000_credits.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  All_STATUS_FILE: artifacts/data_validation/overall_validation_status.txt
  

data_transformation:
  root_dir: artifacts/data_transformation
  data_path1: artifacts/data_ingestion/tmdb_5000_data_kaggle/tmdb_5000_movies.csv
  data_path2: artifacts/data_ingestion/tmdb_5000_data_kaggle/tmdb_5000_credits.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  movie_model: movie_list.pkl
  similarity_model: similarity.pkl

model_prediction:
  movie_model_path: artifacts/model_trainer/movie_list.pkl
  similarity_model_path: artifacts/model_trainer/similarity.pkl  